### PR TITLE
change PES_PER_NODE to MAX_MPITASKS_PER_NODE

### PR DESCRIPTION
**Pull request by jedwards4b**
Change variable PES_PER_NODE to MAX_MPITASKS_PER_NODE
needed for cime compatiblity.

### CODE REVIEW

**Review by fvitt — COMMENTED** [review]
How is MAX_MPITASKS_PER_NODE different then MAX_TASKS_PER_NODE?

**Comment by jedwards4b** [comment]
MAX_TASKS_PER_NODE is the maximum number of tasks*threads allowed on a node.
So on yellowstone MAX_TASKS_PER_NODE=32 MAX_MPITASKS_PER_NODE=16
means that you can have 16 mpitasks and 2 threads per task run on a single node.

**Comment by fvitt** [comment]
Should MAX_TASKS_PER_NODE be renamed as MAX_THREADS_PER_NODE?

**Comment by fischer-ncar** [comment]
I think MAX_TASKS_PER_NODE is fine, because it's mpitasks*threads.

**Comment by brian-eaton** [comment]
I agree with Francis.

max_mpitasks_per_node * threads_per_task = max_threads_per_node.

**Comment by mvertens** [comment]
Please submit this issue in the esmci github repository and not the
cesm-development cime repository. That is no longer being used to track
issues.

**Pull request merged**
