### PR TITLE
remove broken waccm compsets, add BW1850 compset

### PR DESCRIPTION
**Pull request by fvitt**
modified:   config_compsets.xml
        modified:   config_pes.xml
        modified:   testlist_allactive.xml

### CODE REVIEW

**Comment by fvitt** [comment]
Please review and merge with master if okay.
Only tested waccm (BW1850) on cheyenne.

**Review by fischer-ncar — COMMENTED** [review]
I thought the WACCM compsets were suppose to be B1850Cw.   Did we decide to go with BW1850? @jedwards4b @mvertens

**Comment by mvertens** [comment]
I thought so also. Francis -can you please comment?

**Comment by fvitt** [comment]
The WACCM group is insisting on this name.

**Comment by fvitt** [comment]
I changed alias BW1850 to B1850Cw

**Review by fischer-ncar — APPROVED** [review]

**Pull request merged**
